# Generated by Django 2.2.4 on 2019-12-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191212_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('p_status', models.CharField(max_length=20)),
                ('bid_price', models.IntegerField()),
                ('dics', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='products/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
    ]
