# Generated by Django 2.2.4 on 2019-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='acc_image/')),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
